/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const MeditationSession = IDL.Record({
  'duration' : IDL.Nat,
  'sessionType' : IDL.Text,
  'timestamp' : Time,
});
export const MoodEntry = IDL.Record({
  'note' : IDL.Opt(IDL.Text),
  'score' : IDL.Nat,
  'timestamp' : Time,
});

export const idlService = IDL.Service({
  'addAffirmation' : IDL.Func([IDL.Text], [], []),
  'addHealthTip' : IDL.Func([IDL.Text], [], []),
  'getMeditationHistory' : IDL.Func(
      [],
      [IDL.Vec(MeditationSession)],
      ['query'],
    ),
  'getMoodHistory' : IDL.Func([], [IDL.Vec(MoodEntry)], ['query']),
  'getRandomAffirmation' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
  'getRandomHealthTip' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
  'getTotalMeditationMinutes' : IDL.Func([], [IDL.Nat], ['query']),
  'logMeditation' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'logMood' : IDL.Func([IDL.Nat, IDL.Opt(IDL.Text)], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const MeditationSession = IDL.Record({
    'duration' : IDL.Nat,
    'sessionType' : IDL.Text,
    'timestamp' : Time,
  });
  const MoodEntry = IDL.Record({
    'note' : IDL.Opt(IDL.Text),
    'score' : IDL.Nat,
    'timestamp' : Time,
  });
  
  return IDL.Service({
    'addAffirmation' : IDL.Func([IDL.Text], [], []),
    'addHealthTip' : IDL.Func([IDL.Text], [], []),
    'getMeditationHistory' : IDL.Func(
        [],
        [IDL.Vec(MeditationSession)],
        ['query'],
      ),
    'getMoodHistory' : IDL.Func([], [IDL.Vec(MoodEntry)], ['query']),
    'getRandomAffirmation' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
    'getRandomHealthTip' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
    'getTotalMeditationMinutes' : IDL.Func([], [IDL.Nat], ['query']),
    'logMeditation' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'logMood' : IDL.Func([IDL.Nat, IDL.Opt(IDL.Text)], [], []),
  });
};

export const init = ({ IDL }) => { return []; };