/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface MeditationSession {
  'duration' : bigint,
  'sessionType' : string,
  'timestamp' : Time,
}
export interface MoodEntry {
  'note' : [] | [string],
  'score' : bigint,
  'timestamp' : Time,
}
export type Time = bigint;
export interface _SERVICE {
  'addAffirmation' : ActorMethod<[string], undefined>,
  'addHealthTip' : ActorMethod<[string], undefined>,
  'getMeditationHistory' : ActorMethod<[], Array<MeditationSession>>,
  'getMoodHistory' : ActorMethod<[], Array<MoodEntry>>,
  'getRandomAffirmation' : ActorMethod<[], [] | [string]>,
  'getRandomHealthTip' : ActorMethod<[], [] | [string]>,
  'getTotalMeditationMinutes' : ActorMethod<[], bigint>,
  'logMeditation' : ActorMethod<[bigint, string], undefined>,
  'logMood' : ActorMethod<[bigint, [] | [string]], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];